#Trabalho de Otimização
Carolina Frank Abdu e Rafaella Lenzi Romano

##Bibliotecas



In [3]:
import numpy as np
import sympy as sp
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D



#Função 1:
$$
\min f(x) = \sum_{i=1}^{6} \left( 100 (x_{i+1} - x_i^2)^2 + (1 - x_i)^2 \right)
\quad \text{sujeito a} \quad x \in \mathbb{R}^7
$$

Podemos notar que as parcelas do nosso somatório são valores não negativos, ou seja, o menor valor possível nessa primeira análise seria o zero. Além disso, como queremos minimizar, podemos analisar cada parcela separadamente. Como há dependência de valores, vamos analisar a parcela: $$100 (x_{2} - x_1^2)^2 + (1 - x_1)^2 $$ e depois prosseguir com as próximas.  

Gráfico : https://www.geogebra.org/3d/qjszp48r

##Gradiente
Vamos encontrar os pontos críticos da função $$100 (x_{2} - x_1^2)^2 + (1 - x_1)^2 $$


   $$
   \frac{\partial f}{\partial x_1} = -400 x_1 (x_2 - x_1^2) - 2 (1 - x_1)
   $$


   $$
   \frac{\partial f}{\partial x_2} = 200 (x_2 - x_1^2)
   $$

Pelo segundo gradiente temos que $$x_2=x_1^2,$$ substituindo no primeiro gradiente, podemos notar o ponto crítico (1, 1).

####Observação:
Como no ponto crítico encontrado $x_1=x_2$, podemos analisar apenas essa primeira parcela já que as outras serão iguais também.

##Hessiana
No ponto (1,1), a Hessiana H é:

\begin{bmatrix}
1200x_1^2 - 400x_2 + 2 & -400x_1\\
-400x_1 & 200
\end{bmatrix}
=
\begin{bmatrix}
802 & -400\\
-400 & 200
\end{bmatrix}

Como a matriz é definida positiva, podemos afirmar que (1,1) é minimizador local estrito.

In [4]:
def func1(x):
  x = np.array(x)
  f1 = 100 * (x[1] - x[0]**2)**2 + (1 - x[0])**2
  return f1

def grad_1(x):
  grad = np.zeros(2)
  grad[0] = -400 * x[0] * (x[1] - x[0]**2) + 2 * (x[0] - 1)
  grad[1] = 200 * (x[1] - x[0]**2)
  return grad

def hess_1(x):
  hess = np.zeros((2,2))
  hess[0, 0] = 1200 * x[0]**2 - 400 * x[1] + 2
  hess[0, 1] = hess[1, 0] = -400 * x[0]
  hess[1, 1] = 200
  return hess

def funcao_1(x):
  x = np.array(x)
  f= 0
  for i in range(0, 6):
    f += 100 * (x[i+1] - x[i]**2)**2 + (1 - x[i])**2
  return f

def gradiente_1(x):
  grad = np.zeros(7)
  grad[0] = -400 * x[0] * (x[1] - x[0]**2) + 2 * (x[0] - 1)
  for i in range(1, 6):
    grad[i] = -400 * x[i-1] * (x[i] - x[i-1]**2)+ 2*(x[i-1]-1) + 200 * (x[i] - x[i-1]**2)
  grad[6] = 200 * (x[6] - x[5]**2)
  return grad

def hesssiana_1(x):
  x = sp.symbols('x0:7')
  f = sum(100*(x[i+1] - x[i]**2)**2 + (1 - x[i])**2 for i in range(6))
  Hessian = sp.hessian(f, x)
  return Hessian

def definida_positiva(x):
  A = np.array(hess_1(x))
  autovalores = np.linalg.eigvals(A)
  if np.all(autovalores > 0):
    return True
  else:
    return False

print(func1([1,1]))
print(grad_1([1,1]))
print(hess_1([1,1]))
print(hesssiana_1([1,1,1,1,1,1,1]))
print(gradiente_1([1,1,1,1,1,1,1]))



0
[0. 0.]
[[ 802. -400.]
 [-400.  200.]]
Matrix([[1200*x0**2 - 400*x1 + 2, -400*x0, 0, 0, 0, 0, 0], [-400*x0, 1200*x1**2 - 400*x2 + 202, -400*x1, 0, 0, 0, 0], [0, -400*x1, 1200*x2**2 - 400*x3 + 202, -400*x2, 0, 0, 0], [0, 0, -400*x2, 1200*x3**2 - 400*x4 + 202, -400*x3, 0, 0], [0, 0, 0, -400*x3, 1200*x4**2 - 400*x5 + 202, -400*x4, 0], [0, 0, 0, 0, -400*x4, 1200*x5**2 - 400*x6 + 202, -400*x5], [0, 0, 0, 0, 0, -400*x5, 200]])
[0. 0. 0. 0. 0. 0. 0.]


#Função 2:
$$
\min f(x) = \sum_{i=1}^{100} \left( x_i^4 - 16 x_i^2 + 5 x_i \right)
\quad \text{sujeito a} \quad x \in \mathbb{R}^{100}
$$

Podemos minimizar cada uma das parcelas, pois elas são independentes. Além disso, terão o mesmo valor. Assim, o problema se reduz a encontrar o mínimo da função:
$$f(x) = x^4 -16x^2+5x$$


##Gradiente

   $$
   \frac{\partial f}{\partial x_i} = 4 x^3 -32x +5
   $$

Gráfico :
https://www.geogebra.org/graphing/kmhujh39

Pontos críticos encontrados:
x = -2,903; x = 2,747; x= 0,157

In [51]:
def func2(x):
  x = np.array(x)
  f2 = x[0]**4 - 16 * x[0]**2 + 5 * x[0]
  return f2

def grad_2(x):
  grad = np.zeros(1)
  grad[0] = 4 * x[0]**3 - 32 * x[0] + 5
  return grad

def hess_2(x):
  hess = np.zeros((1, 1))
  hess[0, 0] += 12 * x[0]**2 - 32
  return hess

def definida_positiva(x):
  A = np.array(hess_2(x))
  autovalores = np.linalg.eigvals(A)
  if np.all(autovalores > 0):
    return True
  else:
    return False

## Fazendo no R100:
def funcao_2(x):
  x = np.array(x)
  print(x)
  f2 = 0
  for i in range(0, 100):
    f2 += x[i]**4 - 16 * x[i]**2 + 5 * x[i]
  return f2

def gradiente_2(x):
  grad = np.zeros(100)
  for i in range(0, 100):
    grad[i] = 4 * x[i]**3 - 32 * x[i] + 5
  return grad

def hessiana_2(x):
  h = np.zeros((100, 100))
  for i in range(0, 100):
    h[i, i] += 12 * x[i]**2 - 32
  return h

def p():
  print(func2([0.157]))
  print(grad_2([0.157]))
  print(hess_2([0.157]))
  print(definida_positiva([0.157]))

  print(func2([2.747]))
  print(grad_2([2.747]))
  print(hess_2([2.747]))
  print(definida_positiva([2.747]))

  print(func2([-2.903]))
  print(grad_2([-2.903]))
  print(hess_2([-2.903]))
  print(definida_positiva([-2.903]))

#Função 3:
$$
\min f(x) = (x_1^2 + x_2 - 11)^2 + (x_1 + x_2^2 - 7)^2
\quad \text{sujeito a} \quad x \in \mathbb{R}^2
$$

Podemos observar que o mínimo será zero, já que temos a soma de duas funções não negativas. Um estudo dos candidatos ao mínimo, usando essa simplificação pode ser observado no gráfico a seguir: https://www.geogebra.org/calculator/eh33nvhk

##Gradiente
$$
   \frac{\partial f}{\partial x_1} = 4x_1(x_1^2 + x_2 - 11) + 2(x_1 + x_2^2 - 7)
   $$


   $$
   \frac{\partial f}{\partial x_2} = 2 (x_1^2 + x_2 - 11) + 4x_2(x_1 + x_2^2 - 7)
   $$

  Gráfico: https://www.geogebra.org/3d/g9wx3y3d
  

In [6]:
def func3(x):
  f3 = (x[0]**2 + x[1] - 11)**2 + (x[0] + x[1]**2 - 7)**2
  return f3

def grad_3(x):
  grad = np.zeros(2)
  grad[0] = 4 * x[0] * (x[0]**2 + x[1] - 11) + 2 * (x[0] + x[1]**2 - 7)
  grad[1] = 2 * (x[0]**2 + x[1] - 11) + 4 * x[1] * (x[0] + x[1]**2 - 7)
  return grad

def hess_3(x):
  hess = np.zeros((2, 2))
  hess[0, 0] = 12 * x[0]**2 + 4 * x[1] - 42
  hess[0, 1] = hess[1, 0] = 4 * (x[0] + x[1])
  hess[1, 1] = 12 * x[1]**2 + 4 * x[0] - 26
  return hess


#Busca de Armijo

In [7]:
def armijo(x, gama, d, mi):
  t= 1
  k = 0
  d = np.array(d) #direção de descida
  while f(x+t*d) > f(x) + mi*t*(np.transpose(gradiente(x)))@d:
    t = gama*t
    k = k+1
  return t, k




#Método Gradiente

In [8]:
def metodo_gradiente(x, gama, mi, epsilon):
  x=np.array(x)
  k=0
  i = 0   #Número de iterações
  #while gradiente(x) != 0 :   #provavel ajuste aqui para limitar
  while np.linalg.norm(gradiente(x)) > epsilon and i <1000 :
    d = -gradiente(x)
    t, kn = armijo(x, gama, d, mi)
    x = x + t*d
    k = k + kn
    i = i+1
  return x, k, i




##Método Newton


In [37]:
from re import M
def newton(x,gama, mi,epsilon):
  k=0
  i=0  #Número de iterações
  while np.linalg.norm(gradiente(x))> epsilon and i<10000 :
    d = -(np.linalg.inv(hessiana(x)))@gradiente(x)
    t, kn = armijo(x, gama, d, mi)
    x = x + t*d
    k = k+kn
    i = i+1
  return x, k, i



##Método Quase-Newton

In [38]:
def DFS(x0, x1,H): #para funções mais simples converge mais rápido
  x0 = np.array(x0) #x antigo
  x1 = np.array(x1) #x atual
  p = x1-x0
  q = gradiente(x1)-gradiente(x0)
  if np.linalg.norm(p) != 0 and np.linalg.norm(q) != 0:
    H = H + (p@np.transpose(p))/(np.transpose(p)@q) - (H@q@np.transpose(q)@H)/(np.transpose(q)@H@q)
  else:
    H = H
  return H

def BFGS__(x0, x1,H):
  x0 = np.array(x0) #x antigo
  x1 = np.array(x1) #x atual
  p = x1-x0
  q = gradiente(x1)-gradiente(x0)
  H = H + ((1 + np.transpose(q)@H@q)/(np.transpose(p)@q))@((p@np.transpose(p))/(np.transpose(p)@q)) - (((p@np.tranpose(q)@H)+(H@q@np.transpose(p)))/(np.transpose(p)@q))
  return H

def BFGS(x0, x1, H):
    x0 = np.array(x0)  # x antigo
    x1 = np.array(x1)  # x atual
    p = x1 - x0
    q = gradiente(x1) - gradiente(x0)
    # Ensure p and q are column vectors for matrix operations:
    p = p.reshape(-1, 1)  # Reshape p into a column vector
    q = q.reshape(-1, 1)  # Reshape q into a column vector
    # Calculate terms to avoid repeated calculations and for clarity:
    pTp = p.T @ p #transpose(p) @ p
    p_T_q = p.T @ q #transpose(p) @ q
    H_q = H @ q # H@q
    q_T_H_q = q.T @ H_q #transpose(q) @ H @ q
    # update H:
    if p_T_q != 0: #check to avoid division by zero if p.T @ q = 0
        H = H + (1 + q_T_H_q / p_T_q) * (np.outer(p,p.T) / p_T_q) - ((np.outer(p, (q.T @ H)) + np.outer((H_q), p.T)) / p_T_q) #outer to give matrix products as intended
    return H

def quase_newton(x, gama, mi, epsilon,t):
  #t é o tamnho de H segundo nossas análises
  k=0
  i = 0 #Número de iterações
  H = np.identity(t) #mudar de acordo com a quantidade de variáveis
  while np.linalg.norm(gradiente(x))> epsilon and i <10000:
    d = -H@gradiente(x)
    t, kn = armijo(x, gama, d, mi)
    H = BFGS(x, x+t*d, H)
    x = x + t*d
    k = k + kn
    i = i+1
  return x, k,i




In [39]:
gradiente = grad_2
hessiana = hess_2
def f(x) :
  return func2(x)

x = np.random.rand(1)

print(x)
print(metodo_gradiente(x, 0.4, 0.1, 0.000001))
print(newton(x, 0.4, 0.1,0.000001))
print(quase_newton(x, 0.4, 0.1,0.000001,1))



[0.71575581]
(array([2.74680276]), 99, 25)
(array([0.71575581]), 410000, 10000)
(array([2.74680277]), 3, 7)


In [52]:
gradiente = gradiente_2
hessiana = hessiana_2
def f(x) :
  return funcao_2(x)

x = np.random.rand(100)

print(x)
print(metodo_gradiente(x, 0.4, 0.1, 0.000001))
print(newton(x, 0.4, 0.1,0.000001))
print(quase_newton(x, 0.4, 0.1,0.000001,100))

A saída de streaming foi truncada nas últimas 5000 linhas.
 0.58959437 0.44919487 0.38396019 0.48022167 0.32752826 0.91820407
 0.07893092 0.22297578 0.81727981 0.56658427]
[0.6513965  0.00199769 0.72386522 0.28267351 0.36629962 0.69540079
 0.17505402 0.46089891 0.32042206 0.57090293 0.22642864 0.12207165
 0.45960466 0.82153994 0.97927954 0.89608671 0.7916885  0.32696908
 0.64293058 0.12561408 0.81084504 0.62316705 0.10848125 0.44319084
 0.45750417 0.50374508 0.7949583  0.18996814 0.07127074 0.97676722
 0.15733377 0.73756401 0.35699763 0.50604126 0.02269341 0.61494246
 0.04183266 0.85065842 0.01780559 0.91501729 0.23471406 0.61168112
 0.91049184 0.59064705 0.46579862 0.89662676 0.46418705 0.46883337
 0.56498017 0.73421999 0.87808573 0.43888494 0.86300776 0.25118958
 0.33771644 0.90061944 0.27124357 0.16134676 0.79966496 0.18210163
 0.70982236 0.13522415 0.28216357 0.68846889 0.2317123  0.4888125
 0.71979331 0.41159119 0.31630712 0.61389072 0.17544998 0.83892296
 0.86234584 0.14325053 0.

KeyboardInterrupt: 

In [1]:
gradiente = grad_2
hessiana = hess_2
def f(x) :
  return func2(x)
print(metodo_gradiente([2], 0.5, 0.1, 0.001))
print(newton([2], 0.5, 0.1,0.001))
print(quase_newton([2], 0.5, 0.1,0.001))

NameError: name 'grad_2' is not defined